### ISSUE TITLE
Moving keymaps shouldn't be dot-repeatable by default

### ISSUE THREAD

**Issue by Shatur** [Tummetott/unimpaired.nvim#5]
I noticed that keymaps like `]q` is dot-repeatable by default. Yes, I can disable it, but the default behavior is different from https://github.com/tpope/vim-unimpaired and Neovim in general (all moving operations like `C-o` is not dot-repeatable).

**Comment by tummetott** [comment]
While I was writing this plugin, I thought about this for a while and intentionally decided to make them dot repeatable. I wanted to try, if it brings any benefit. But I think you're right, we should stick to tpopes defaults and change that. Give me some time because I'm a bit busy atm. Or you do a PR yourself.

**Comment by Shatur** [comment]
@tummetott opened #6.
